CREATE OR REPLACE FUNCTION NthHighestSalary(N INT) RETURNS TABLE (Salary INT) AS $$
BEGIN
  IF n <= 0 THEN
    RETURN;
  END IF;

  RETURN QUERY
    SELECT DISTINCT e.salary
    FROM employee e
    ORDER BY salary DESC
    OFFSET n-1 LIMIT 1;
END;
$$ LANGUAGE plpgsql;
